import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, CircleHelp, LockKeyhole, Sparkles } from "lucide-react";
import AuthControls from "@/components/AuthControls";
import { assetUrls } from "@/lib/assets";

type Lesson = { id: string; track: string; title: string; plain: string; tryIt: string; game: string; level: string };

const lessons: Lesson[] = [
  { id: "what-is-ai", track: "Start here", title: "What AI is—and what it is not", plain: "AI finds patterns in examples. It can be useful, but it can also be wrong or overconfident.", tryIt: "Ask an AI to explain one everyday task, then circle the claim you would still verify.", game: "fact", level: "Starter" },
  { id: "better-requests", track: "Ask better", title: "Give the tool a clear job", plain: "A useful request names the goal, context, format and limits instead of saying only ‘do this’. ", tryIt: "Rewrite one vague request by adding the audience, outcome and one constraint.", game: "prompt", level: "Starter" },
  { id: "evidence", track: "Think safely", title: "Separate a claim from evidence", plain: "A confident sentence is not proof. Look for the source, date, method and what remains unknown.", tryIt: "Take one answer you received today and mark known, assumed and still-unknown parts.", game: "source-hunt", level: "Building" },
  { id: "privacy", track: "Use responsibly", title: "Protect information before sharing", plain: "Remove names, private school details, passwords and identifying clues before putting text into a tool.", tryIt: "Redact a sample paragraph and keep only the details the task truly needs.", game: "safety", level: "Building" },
  { id: "systems", track: "Build systems", title: "Turn a goal into steps", plain: "Good AI workflows have an input, a small action, a review checkpoint and a human decision.", tryIt: "Draw four boxes for one repeatable task: input, prompt, check and final choice.", game: "decision-studio", level: "Stretch" },
  { id: "robotics", track: "Make things", title: "How robots follow a plan", plain: "Robots connect a goal to sensors, rules and actions. A test tells us what to repair next.", tryIt: "Describe a robot that notices one signal and takes one safe action.", game: "robotics", level: "Building" },
  { id: "patterns", track: "Play first", title: "Notice the next shape", plain: "Patterns repeat, change or grow. Look at color and shape before you choose what comes next.", tryIt: "Point to the next tile in a simple pattern—no typing needed.", game: "pattern-builder", level: "Ages 5–15" },
  { id: "memory", track: "Play first", title: "Remember the place", plain: "Memory grows with attention. Watch a small visual scene, then find what changed.", tryIt: "Play a short tile memory round and try again to improve your own score.", game: "memory-adventure", level: "Ages 5–15" },
  { id: "science-play", track: "Play first", title: "Make a tiny prediction", plain: "Good science starts with noticing a change and making a careful guess about what may happen.", tryIt: "Choose the visual result that matches the change—then test your idea.", game: "mini-scientist", level: "Ages 5–15" },
];

export default function LearnPage() {
  const [track, setTrack] = useState("All");
  const [completed, setCompleted] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("aifs-learn-completed-v1") || "[]"); } catch { return []; } });
  const visible = useMemo(() => track === "All" ? lessons : lessons.filter((lesson) => lesson.track === track), [track]);
  const tracks = ["All", ...Array.from(new Set(lessons.map((lesson) => lesson.track)))];
  const toggle = (id: string) => setCompleted((previous) => { const next = previous.includes(id) ? previous.filter((item) => item !== id) : [...previous, id]; localStorage.setItem("aifs-learn-completed-v1", JSON.stringify(next)); return next; });
  return <div className="topics-page" data-testid="learn-ai-page"><header className="game-header"><a className="game-brand" href="/"><img src={assetUrls.mark} alt="" /><span><strong>AI</strong> for <em>Students</em></span></a><a className="game-return" href="/"><ArrowLeft size={15} /> Back to the desk</a><AuthControls /></header><main className="topics-main"><section className="topics-hero"><span className="game-kicker">LEARN AI / A CLEAR START</span><h1>Build your AI<br /><em>foundation.</em></h1><p>Short lessons, one useful idea at a time. Learn the concept, try it in your own words, then practice it in a game.</p><div className="learn-progress-strip"><span><strong>{completed.length}</strong> of {lessons.length} lessons tried</span><span>{completed.length === lessons.length ? "Foundation complete" : "Keep one small promise today"}</span></div></section><section className="learn-path-panel"><div className="learn-panel-heading"><div><span className="game-kicker">CHOOSE A TRACK</span><h2>Where do you want to begin?</h2></div><BookOpen size={22} /></div><div className="topic-filters">{tracks.map((item) => <button key={item} className={track === item ? "is-active" : ""} onClick={() => setTrack(item)}>{item}</button>)}</div></section><section className="learn-grid" aria-label="AI lessons">{visible.map((lesson, index) => <article className={`learn-card ${completed.includes(lesson.id) ? "is-complete" : ""}`} key={lesson.id}><div className="learn-card-top"><span>0{index + 1}</span><span>{lesson.level}</span></div><span className="learn-track">{lesson.track}</span><h2>{lesson.title}</h2><p>{lesson.plain}</p><div className="learn-try"><Sparkles size={15} /><span><strong>Try it</strong>{lesson.tryIt}</span></div><div className="learn-card-footer"><button type="button" onClick={() => toggle(lesson.id)}>{completed.includes(lesson.id) ? <><Check size={15} /> Tried</> : <>Mark tried <ArrowRight size={15} /></>}</button>{lesson.game === "robotics" ? <a href="/robotics">Open Robotics <ArrowRight size={14} /></a> : lesson.game === "pattern-builder" || lesson.game === "memory-adventure" || lesson.game === "mini-scientist" ? <a href={`/discovery-lab?game=${lesson.game}`}>Play visual challenge <ArrowRight size={14} /></a> : <a href={`/play?game=${lesson.game}`}>Practice game <ArrowRight size={14} /></a>}</div></article>)}</section><aside className="learn-safety-note"><LockKeyhole size={18} /><p><strong>Learning boundary:</strong> These lessons teach practical habits. They do not measure intelligence, predict careers or replace a teacher’s judgment.</p></aside><div className="topics-empty" hidden={visible.length > 0}><CircleHelp size={18} /><p>No lesson matched this track yet.</p></div></main><footer className="game-page-footer"><span>AI for Students</span><span>Learn the tool. Keep the thinking.</span></footer></div>;
}
