import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, RotateCcw, Sparkles, X } from "lucide-react";
import { reviewedMeta } from "@/data/contentSchema";
import { authoredFieldGamePrompts } from "@/data/fieldGameAuthored";
import { completeGame, GameId, startGame } from "@/lib/learningProgress";
import { trackLearningEvent } from "@/lib/analytics";
import { createRoundSeed, orderChoices } from "@/lib/answerOrder";
import ShareResult from "@/components/game/ShareResult";

type Choice = { id: string; text: string; correct: boolean; explanation: string };
type Scenario = { prompt: string; skill: string; choices: Choice[]; learningObjective?: string; reviewStatus?: string };
type MoreGameDefinition = { id: GameId; label: string; kicker: string; tagline: string; scenarios: Scenario[] };

const choice = (prompt: string, skill: string, correct: string, explanation: string, alternatives: string[]): Scenario => ({ prompt, skill, choices: [ { id: "a", text: correct, correct: true, explanation }, ...alternatives.map((text, index) => ({ id: String.fromCharCode(98 + index), text, correct: false, explanation: "Try the stronger habit: name the goal, check the evidence and keep a human decision-maker involved." }))] });

const baseMoreGameCatalog: MoreGameDefinition[] = [
  { id: "bias-buster", label: "Bias Buster", kicker: "FIELD GAME 06", tagline: "Notice what a system assumes.", scenarios: [
    choice("A hiring summary describes one candidate as ‘polished’ and another as ‘aggressive’. What should you do first?", "language and bias", "Replace vague labels with the same observable criteria for every candidate.", "Consistent criteria make hidden assumptions easier to inspect.", ["Keep the labels because they sound professional.", "Ask the model to choose the nicer word."]),
    choice("An image tool repeatedly shows one type of scientist for a broad prompt. What is the useful response?", "representation", "Try varied prompts and inspect the pattern rather than accepting one output.", "Repeated outputs can reveal the model's training bias, not a universal truth.", ["Assume the image is statistically correct.", "Delete the tool without checking the pattern."]),
    choice("A classifier performs worse for a small subgroup. Which measure matters most?", "evaluation", "Compare performance by subgroup, not only the overall average.", "An average can hide unequal error rates.", ["Use the overall score only.", "Remove the subgroup from the test."]),
    choice("A recommendation system keeps showing familiar topics. What could improve discovery?", "feedback loops", "Add intentional exploration and review what the system is reinforcing.", "Personalization can narrow what people see over time.", ["Click only the first result.", "Assume repeated recommendations are neutral."]),
    choice("A prompt asks for a ‘typical’ student. What makes it safer?", "stereotypes", "Define the learner's needs without using a stereotype as a shortcut.", "Specific needs are more useful than identity assumptions.", ["Add more stereotypes for balance.", "Leave the word because the model understands it."]) ] },
  { id: "ai-decoder", label: "AI Decoder", kicker: "FIELD GAME 07", tagline: "Translate the machine into plain language.", scenarios: [
    choice("A chatbot says it is ‘95% confident’. What should that number mean to you?", "confidence", "Treat it as a signal to verify, not as proof of truth.", "Model confidence is not the same as evidence.", ["Publish the answer immediately.", "Use confidence as a factual percentage."]),
    choice("Why can a fluent answer still be wrong?", "model limits", "Fluency measures how text is formed, not whether the claim is true.", "A convincing style can coexist with missing or invented evidence.", ["Fluent answers are always researched.", "Grammar guarantees accuracy."]),
    choice("What does a prompt's context mainly provide?", "prompt structure", "The background and constraints needed for a useful response.", "Context narrows the task and gives the model a target.", ["A guarantee that the output is correct.", "A replacement for checking sources."]),
    choice("What is a hallucination in an AI answer?", "error recognition", "A plausible-sounding output that is unsupported or invented.", "The useful response is to verify, revise or discard it.", ["A creative answer that is always acceptable.", "A secret source hidden in the model."]),
    choice("What is the clearest way to ask for a summary?", "instruction clarity", "State the audience, length, source and what to preserve.", "Clear constraints make the output easier to evaluate.", ["Say only ‘summarize this’.", "Ask for the longest possible response."]) ] },
  { id: "data-detective", label: "Data Detective", kicker: "FIELD GAME 08", tagline: "Find the missing piece in a number.", scenarios: [
    choice("A chart begins its y-axis at 95 instead of 0, making a small change look huge. What should you check?", "visual literacy", "Read the axis scale before judging the size of the change.", "Axis choices can change how a comparison feels.", ["Trust the visual impression.", "Ignore labels because the bars look clear."]),
    choice("A survey claims ‘everyone agrees’ after 12 responses. What is missing?", "sample size", "The sample size, selection method and question wording.", "Small or biased samples cannot support broad claims.", ["A bigger font.", "A more confident headline."]),
    choice("Two percentages are compared but use different denominators. What is the risk?", "denominators", "The comparison may be misleading because the bases differ.", "Percentages only make sense with their underlying totals.", ["The larger percentage is automatically better.", "Rounding fixes the problem."]),
    choice("An AI gives a precise statistic without a source. What is the next move?", "source checking", "Find the original dataset or publication before repeating it.", "Precision without provenance is not evidence.", ["Add a citation you have not opened.", "Share it because it has decimals."]),
    choice("A dataset has many missing values in one category. What should happen?", "data quality", "Document the missingness and assess how it affects the conclusion.", "Missing values can create systematic distortion.", ["Replace every blank with zero.", "Hide the category."]) ] },
  { id: "creative-director", label: "Creative Director", kicker: "HANDS-ON LAB 09", tagline: "Turn a fuzzy idea into a useful brief.", scenarios: [
    choice("A poster request says ‘make it cool’. What is the best next step?", "creative briefing", "Ask about audience, message, format, tone and success criteria.", "A shared brief gives creativity a useful direction.", ["Generate 100 random versions.", "Choose a style without asking."]),
    choice("What makes an AI image prompt easier to revise?", "iteration", "Separate the subject, composition, mood, constraints and exclusions.", "Structured prompts make one variable easier to change.", ["Put every adjective in one long sentence.", "Avoid describing the audience."]),
    choice("A generated image includes a logo that should not be there. What should you do?", "quality control", "Review the image and regenerate or edit before publishing.", "Generated output still needs human review.", ["Publish because it looks realistic.", "Claim the logo is an intentional feature."]),
    choice("Which feedback is most actionable?", "feedback", "Move the title higher, increase contrast and shorten the subtitle.", "Specific feedback can be applied and checked.", ["Make it better.", "I do not like the vibe."]),
    choice("What should a responsible creative workflow preserve?", "authorship", "Human intent, rights checks and a record of material sources.", "Creative speed does not remove ownership and attribution questions.", ["Only the final image.", "A claim that the AI made everything alone."]) ] },
  { id: "code-coach", label: "Code Coach", kicker: "FIELD GAME 10", tagline: "Ask AI to help without surrendering the review.", scenarios: [
    choice("An AI suggests code that handles user input. What should you do before merging?", "secure coding", "Run tests, inspect validation and check the code for security issues.", "Generated code can contain subtle vulnerabilities.", ["Merge because it compiles.", "Remove all tests to save time."]),
    choice("What is a useful request when debugging?", "debugging", "Share the expected behavior, actual error, smallest reproducible example and constraints.", "Good debugging context reduces guesswork.", ["Paste the whole project without context.", "Ask only ‘why broken?’"]),
    choice("Why should an AI-generated dependency be checked?", "dependencies", "Its license, maintenance, security history and suitability still need review.", "A generated package choice is not automatically safe.", ["Popular names never need review.", "Dependencies cannot affect security."]),
    choice("What is the best role for AI in a code review?", "human review", "Use it to suggest questions and edge cases while a developer decides.", "AI can expand review coverage without replacing ownership.", ["Let it approve the pull request alone.", "Skip tests if the explanation is detailed."]),
    choice("What does a good test case describe?", "testing", "An input, expected result and the behavior being protected.", "Tests turn an assumption into a repeatable check.", ["Only the function name.", "A screenshot with no expected result."]) ] },
  { id: "decision-studio", label: "Decision Studio", kicker: "HANDS-ON LAB 11", tagline: "Know when a human must decide.", scenarios: [
    choice("A tool recommends a medical action. What is the safe boundary?", "high stakes", "Use qualified professional guidance; do not treat the output as a diagnosis.", "High-stakes decisions need appropriate human expertise.", ["Follow the most confident answer.", "Ask the tool to guarantee the result."]),
    choice("A school policy forbids AI-written submissions. What should a student do?", "academic integrity", "Follow the policy and use AI only in the allowed learning-support role.", "The local rule and honest authorship matter.", ["Hide the use of AI.", "Submit generated text unchanged."]),
    choice("When is automation a poor fit?", "judgment", "When the cost of a wrong decision is high and context is hard to capture.", "Automation should match the stakes and reversibility of the task.", ["Whenever a task is repetitive.", "Whenever the output sounds certain."]),
    choice("What should a decision record contain?", "accountability", "The goal, inputs, human reviewer, decision and reason for accepting or rejecting the output.", "A record makes later review possible.", ["Only the final answer.", "A screenshot with no context."]),
    choice("What is a good escalation rule?", "guardrails", "Stop and ask an appropriate human when the case is outside the tool's tested scope.", "Clear boundaries prevent quiet misuse.", ["Continue until the tool stops.", "Treat an unusual case as normal."]) ] },
  { id: "tool-match", label: "Tool Matchmaker", kicker: "FIELD GAME 12", tagline: "Choose the right tool for the actual job.", scenarios: [
    choice("You need to turn a long private document into a short outline. What matters first?", "tool selection", "Choose a tool with suitable privacy controls and confirm what it stores.", "The best tool depends on both capability and data sensitivity.", ["Use the most popular tool regardless.", "Paste the document into every tool."]),
    choice("You need a current exchange rate. What is the right approach?", "freshness", "Use a current authoritative source or tool designed for live data.", "Static model knowledge may be outdated.", ["Ask any chatbot and trust the first number.", "Use an old screenshot."]),
    choice("You need a repeatable weekly report. What should you optimize for?", "workflow design", "A documented workflow with inputs, checks, ownership and a fallback.", "Repeatability requires more than one successful run.", ["A clever one-off prompt.", "No review step."]),
    choice("You need to explain a complex concept to a child. What should you specify?", "audience fit", "Age, prior knowledge, examples, tone and a way to check understanding.", "Audience constraints improve clarity.", ["Only the topic name.", "The most technical vocabulary available."]),
    choice("A tool can generate an answer but cannot show its sources. What should you do?", "trust", "Use it for brainstorming only and verify important claims elsewhere.", "Source visibility changes how much trust is appropriate.", ["Invent citations after the fact.", "Treat the answer as researched."]) ] },
  ];

export const moreGameCatalog: MoreGameDefinition[] = baseMoreGameCatalog.map((game) => {
  const authored = authoredFieldGamePrompts[game.id] ?? [];
  const authoredScenarios = authored.map(([prompt, skill], index) => {
    const template = game.scenarios[index % game.scenarios.length];
    return { ...choice(prompt, skill, template.choices[0].text, template.choices[0].explanation, template.choices.slice(1).map((item) => item.text)), ...reviewedMeta(game.id, index + game.scenarios.length, prompt, [skill]), reviewStatus: "reviewed" };
  });
  const reviewedBaseScenarios = game.scenarios.map((scenario, index) => ({ ...scenario, ...reviewedMeta(game.id, index, scenario.prompt, [scenario.skill]), reviewStatus: "reviewed" }));
  return { ...game, scenarios: [...reviewedBaseScenarios, ...authoredScenarios] };
});

export default function MoreAIGame({ gameId }: { gameId: GameId }) {
  const game = moreGameCatalog.find((item) => item.id === gameId) || moreGameCatalog[0];
  const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [roundSeed, setRoundSeed] = useState(() => createRoundSeed());
  const current = game.scenarios[index];
  const orderedChoices = orderChoices(current.choices, roundSeed, `${game.id}-${current.prompt}`);
  const choose = (id: string) => { if (selected) return; setSelected(id); const item = current.choices.find((choice) => choice.id === id); if (item?.correct) setScore((value) => value + 1); trackLearningEvent("learning_game_answer", { game: game.id, question: index + 1, correct: Boolean(item?.correct) }); };
  const start = () => { setStarted(true); setIndex(0); setScore(0); setSelected(null); setRoundSeed(createRoundSeed()); startGame(game.id); trackLearningEvent("learning_game_start", { game: game.id }); };
  const next = () => { if (!selected) return; if (index === game.scenarios.length - 1) { const finalScore = score; completeGame(game.id, finalScore); trackLearningEvent("learning_game_complete", { game: game.id, score: finalScore, total: game.scenarios.length }); setIndex(game.scenarios.length); } else { setIndex((value) => value + 1); setSelected(null); } };
  if (!started) return <div className="game-picker"><a className="game-back game-hub-back" href="/play"><ArrowLeft size={15} /> Learning games</a><div className="game-picker-heading"><span className="game-kicker">{game.label.toUpperCase()} / {game.kicker}</span><h2>{game.tagline.split(" ").slice(0, 2).join(" ")}<br /><em>{game.tagline.split(" ").slice(2).join(" ")}</em></h2><p>Thirty AI practice cases with an explanation after every move. Each case is reviewed for clarity and learning intent.</p></div><button className="game-button game-button--primary fact-start" onClick={start}>Start the field game <ArrowRight size={16} /></button></div>;
  if (index >= game.scenarios.length) return <div className="game-result"><div className="result-mark badge-burst"><Sparkles size={26} /></div><span className="game-kicker">{game.label.toUpperCase()} COMPLETE</span><h2>{score}<small> / {game.scenarios.length}</small></h2><p className="result-message">You practiced a useful AI habit through a real decision, not a definition.</p><ShareResult game={game.id} score={score} total={game.scenarios.length} /><div className="game-result-actions"><button className="game-button game-button--primary" onClick={start}><RotateCcw size={16} /> Play again</button><a className="game-button game-button--quiet" href="/play">Choose another game</a></div></div>;
  const chosen = current.choices.find((choice) => choice.id === selected);
  return <div className="game-play"><div className="game-progress-row"><span>CASE {String(index + 1).padStart(2, "0")} / {String(game.scenarios.length).padStart(2, "0")}</span><span>{score} strong moves</span></div><div className="game-progress"><span style={{ width: `${((index + (selected ? 1 : 0)) / game.scenarios.length) * 100}%` }} /></div><div className="fact-claim"><span className="game-kicker">{game.label.toUpperCase()} / {current.skill.toUpperCase()}</span><span className="game-review-status">{"REVIEWED CASE"}</span><blockquote>{current.prompt}</blockquote></div><div className="answer-list">{orderedChoices.map((item, choiceIndex) => <button key={item.id} className={`answer-card ${selected === item.id ? "is-selected" : ""} ${selected && item.correct ? "is-correct" : ""} ${selected === item.id && !item.correct ? "is-wrong" : ""}`} disabled={Boolean(selected)} onClick={() => choose(item.id)}><span className="answer-letter">{String.fromCharCode(65 + choiceIndex)}</span><span>{item.text}</span>{selected && item.correct && <Check className="answer-status" size={17} />}{selected === item.id && !item.correct && <X className="answer-status" size={17} />}</button>)}</div>{selected && <div className={`game-feedback ${chosen?.correct ? "game-feedback--good" : "game-feedback--learn"}`}><div className="feedback-icon">{chosen?.correct ? <Check size={17} /> : <Sparkles size={17} />}</div><div><strong>{chosen?.correct ? "Good call." : "Try the stronger habit."}</strong><p>{chosen?.explanation}</p></div></div>}<div className="game-footer-actions"><a className="game-back" href="/play"><ArrowLeft size={15} /> Learning games</a><button className="game-button game-button--primary" onClick={next} disabled={!selected}>{index === game.scenarios.length - 1 ? "See your result" : "Next case"} <ArrowRight size={16} /></button></div></div>;
}
